#ifndef PARAMETER_H
#define PARAMETER_H

/*
    【EEPROM空间分配情况】
    0-7         开机默认电压电流         8字节
	8-15        出厂限制电压电流         8字节
    16-55       用户存储电压电流（5组）  40字节
    56-95       工厂模式的显式参数       40字节
    96-127      工厂模式的隐式参数       32字节
*/

#define BYTES_EEPROM_ADDR_START_DEFAULT   8
#define BYTES_EEPROM_ADDR_START_USER      40
#define BYTES_EEPROM_ADDR_START_LIMIT     8
#define BYTES_EEPROM_ADDR_START_CAL_RAW   40
#define BYTES_EEPROM_ADDR_START_CAL_DATA  32

#define EEPROM_ADDR_START_DEFAULT   0
#define EEPROM_ADDR_START_USER      ((BYTES_EEPROM_ADDR_START_DEFAULT)/8)
#define EEPROM_ADDR_START_LIMIT     ((BYTES_EEPROM_ADDR_START_DEFAULT+BYTES_EEPROM_ADDR_START_USER)/8)
#define EEPROM_ADDR_START_CAL_RAW   ((BYTES_EEPROM_ADDR_START_DEFAULT+BYTES_EEPROM_ADDR_START_USER+BYTES_EEPROM_ADDR_START_LIMIT)/8)
#define EEPROM_ADDR_START_CAL_DATA  ((BYTES_EEPROM_ADDR_START_DEFAULT+BYTES_EEPROM_ADDR_START_USER+BYTES_EEPROM_ADDR_START_LIMIT+BYTES_EEPROM_ADDR_START_CAL_RAW)/8)

#define MAX_USER_ITEM	5
#define MIN_USER_ITEM	1

#define COEFFICIENT_SETING_V_LIMIT 	12
#define COEFFICIENT_SETING_I_LIMIT 	12
#define COEFFICIENT_SETING_V_REF   	12
#define COEFFICIENT_SETING_I_REF   	12
#define COEFFICIENT_SETING_V       	12
#define COEFFICIENT_SETING_I       	12
#define COEFFICIENT_PWM            	1
#define COEFFICIENT_ADJ_V          	12
#define COEFFICIENT_ADJ_I          	12
#define COEFFICIENT_READ           	255
#define COEFFICIENT_WRITE          	255

/*计时有关*/
#define TIME_DITHER 10
#define TIME_BUTTONDOWN_LONG 20
#define TIME_BUTTONDOWN_LONGLONG 120

#define TIMEOUT_MS 5000
#define TIMEOUT_COUNTS (5000/(25*10))

#define WAIT_TIME_FOR_GOING_TO_FACTORY_MENU_MS 3000 /*ms*/
#define WAIT_TIME_FOR_GOING_TO_FACTORY_MENU_COUNTS (WAIT_TIME_FOR_GOING_TO_FACTORY_MENU_MS/(25*10)) /*循环次数*/

#define WAIT_TIME_FOR_LONG_PUSH_MS 500 /*ms*/
#define WAIT_TIME_FOR_LONG_PUSH_COUNTS  (WAIT_TIME_FOR_LONG_PUSH_MS/25) /*循环次数*/

#define WAIT_TIME_FOR_SHORTSHORT_PUSH_MS 500 /*ms*/
#define WAIT_TIME_FOR_SHORTSHORT_PUSH_COUNTS  (WAIT_TIME_FOR_SHORTSHORT_PUSH_MS/25) /*循环次数*/


#define MAX_PWM_DATA 15000
#define MIN_PWM_DATA 0

#define MAX_V_LIMIT 12000 /*120V，电压乘以100倍*/
#define MIN_V_LIMIT 0

#define MAX_I_LIMIT 900 /*90A，电流乘以100倍*/
#define MIN_I_LIMIT 0


#endif //#ifndef PARAMETER_H
